# Generated by Django 5.2.14 on 2026-05-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(blank=True, max_length=7, unique=True, verbose_name='placa')),
                ('brand', models.CharField(max_length=80, verbose_name='marca')),
                ('model', models.CharField(max_length=120, verbose_name='modelo')),
                ('version', models.CharField(max_length=160, verbose_name='versao')),
                ('year', models.PositiveIntegerField(verbose_name='ano')),
                ('engine', models.CharField(blank=True, max_length=40, verbose_name='motor')),
                ('fuel', models.CharField(blank=True, max_length=40, verbose_name='combustivel')),
                ('fipe_code', models.CharField(blank=True, max_length=20, verbose_name='codigo FIPE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand', 'model', 'version', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('oleo', 'Oleo do motor'), ('filtro_oleo', 'Filtro de oleo'), ('filtro_ar', 'Filtro de ar'), ('bieleta', 'Bieleta'), ('pastilha_freio', 'Pastilha de freio'), ('vela', 'Vela'), ('outro', 'Outro')], max_length=40, verbose_name='categoria')),
                ('name', models.CharField(max_length=140, verbose_name='nome')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='marca da peca')),
                ('code', models.CharField(max_length=80, verbose_name='codigo')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compatible_vehicles', models.ManyToManyField(blank=True, related_name='compatible_parts', to='catalog.vehicle', verbose_name='veiculos compativeis')),
            ],
            options={
                'ordering': ['category', 'brand', 'code'],
                'unique_together': {('brand', 'code')},
            },
        ),
    ]
