# Generated by Django 5.2.14 on 2026-05-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='compatible_vehicles',
            field=models.ManyToManyField(blank=True, related_name='compatible_parts', to='catalog.vehicle', verbose_name='modelos compativeis'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(blank=True, max_length=7, verbose_name='placa de referencia'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('brand', 'model', 'version', 'year', 'engine')},
        ),
    ]
