# Generated by Django 5.2.14 on 2026-05-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_part_compatible_vehicles_alter_vehicle_plate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='plate',
        ),
    ]
