# Generated by Django 5.2.14 on 2026-05-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_alter_part_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='barcode',
            field=models.CharField(blank=True, max_length=40, verbose_name='codigo de barras'),
        ),
        migrations.AddField(
            model_name='part',
            name='last_purchase_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='ultima quantidade comprada'),
        ),
        migrations.AddField(
            model_name='part',
            name='last_purchase_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ultimo total comprado'),
        ),
        migrations.AddField(
            model_name='part',
            name='last_purchase_unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='ultimo custo unitario'),
        ),
        migrations.AddField(
            model_name='part',
            name='ncm',
            field=models.CharField(blank=True, max_length=20, verbose_name='NCM'),
        ),
        migrations.AddField(
            model_name='part',
            name='unit',
            field=models.CharField(blank=True, max_length=10, verbose_name='unidade'),
        ),
    ]
