# Generated by Django 5.2.14 on 2026-05-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_part_barcode_part_last_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fipe_brand_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='codigo marca FIPE'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fipe_model_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='codigo modelo FIPE'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fipe_vehicle_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='tipo FIPE'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fipe_year_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='codigo ano FIPE'),
        ),
    ]
